import type { Metadata, Viewport } from "next";
import { Orbit } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "@/components";
import AuthContext from "@/context/AuthContext";

const orbit = Orbit({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-orbit",
});
const nanum_square_neo = localFont({
  src: "../public/asset/font/NanumSquareNeo-Variable.woff2",
  display: "swap",
  variable: "--font-nsn",
});

export const viewport: Viewport = {
  themeColor: "#121212",
};

export const metadata: Metadata = {
  title: "Create Next Archive",
  description: "Generated by create next archive",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="kr"
      className={`${orbit.variable} ${nanum_square_neo.variable}`}
    >
      <body>
        <AuthContext>
          <Header></Header>
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
